# PyTorch Basics: NumPy vs PyTorch
This notebook is organized into small sections that compare NumPy and PyTorch for common tensor and matrix operations.
We will cover:
- matrix transpose
- dot product
- matrix multiplication
- softmax
- logarithms and cross-entropy intuition

In [ ]:
# NumPy is used for arrays and mathematical operations
import numpy as np

# torch is the main PyTorch package for tensor operations
import torch

# torch.nn contains neural network layers and functions such as Softmax
import torch.nn as nn

# Set a random seed so random values stay the same each time you run the notebook
np.random.seed(7)
torch.manual_seed(7)

## 1. Matrix Transpose
The transpose swaps rows and columns of a matrix.
If the original matrix has shape `(2, 5)`, its transpose will have shape `(5, 2)`.

In [ ]:
# Create a 2 x 5 matrix using NumPy
numpy_matrix = np.asarray([[1, 0, 2, 5, -2], [1, 0, 2, 5, -2]])

# .shape shows the size as (rows, columns)
print('Original NumPy shape:', numpy_matrix.shape)

# .T means transpose, so rows become columns and columns become rows
numpy_transpose = numpy_matrix.T
print('Transposed NumPy shape:', numpy_transpose.shape)

# Print the new matrix so we can see the row/column swap
print(numpy_transpose)

Original NumPy shape: (2, 5)
Transposed NumPy shape: (5, 2)
[[ 1  1]
 [ 0  0]
 [ 2  2]
 [ 5  5]
 [-2 -2]]


In [ ]:
# Create the same 2 x 5 matrix using a PyTorch tensor
torch_matrix = torch.tensor([[1, 0, 2, 5, -2], [1, 0, 2, 5, -2]])

# PyTorch tensors also have a shape
print('Original PyTorch shape:', torch_matrix.shape)

# .T does the transpose in PyTorch too
torch_transpose = torch_matrix.T
print('Transposed PyTorch shape:', torch_transpose.shape)

# Print the transposed tensor
print(torch_transpose)

Original PyTorch shape: torch.Size([2, 5])
Transposed PyTorch shape: torch.Size([5, 2])
tensor([[ 1,  1],
        [ 0,  0],
        [ 2,  2],
        [ 5,  5],
        [-2, -2]])


## 2. Dot Product
The dot product multiplies matching elements and adds them together.
It is defined for vectors with the same length.

In [ ]:
# Create two 1D NumPy vectors of the same length
nv1 = np.array([1, 2, 3, 4])
nv2 = np.array([1, 2, 3, 4])

# np.dot multiplies matching positions and then adds the results
print('np.dot:', np.dot(nv1, nv2))

# This line shows the same idea in two steps: multiply first, then sum
print('elementwise multiply + sum:', np.sum(nv1 * nv2))

np.dot: 30
elementwise multiply + sum: 30


In [ ]:
# Create two 1D PyTorch tensors of the same length
tv1 = torch.tensor([1, 2, 3, 4])
tv2 = torch.tensor([1, 2, 3, 4])

# torch.dot computes the dot product directly
print('torch.dot:', torch.dot(tv1, tv2))

# This is the same calculation written as multiply first, then sum
print('elementwise multiply + sum:', torch.sum(tv1 * tv2))

torch.dot: tensor(30)
elementwise multiply + sum: tensor(30)


## 3. Matrix Multiplication
For matrix multiplication, the number of columns in the first matrix must match the number of rows in the second matrix.
Here `(3, 2) x (2, 3)` produces a `(3, 3)` result.

In [ ]:
# Create a 3 x 2 matrix with random values
m1 = np.random.rand(3, 2)

# Create a 2 x 3 matrix with random values
m2 = np.random.rand(2, 3)

# Matrix multiplication is valid because the inner sizes match: 2 and 2
numpy_result = np.matmul(m1, m2)

# Show both input matrices
print('Matrix 1:\n', m1)
print('Matrix 2:\n', m2)

# Show the multiplication result and its shape
print('NumPy matmul result:\n', numpy_result)
print('Result shape:', numpy_result.shape)

Matrix 1:
 [[0.07630829 0.77991879]
 [0.43840923 0.72346518]
 [0.97798951 0.53849587]]
Matrix 2:
 [[0.50112046 0.07205113 0.26843898]
 [0.4998825  0.67923    0.80373904]]
NumPy matmul result:
 [[0.4281074  0.53524234 0.6473353 ]
 [0.58134342 0.52298713 0.69916333]
 [0.75927522 0.4362278  0.69534066]]
Result shape: (3, 3)


In [ ]:
# Create a 3 x 2 PyTorch matrix with random values
m1_torch = torch.randn(3, 2)

# Create a 2 x 3 PyTorch matrix with random values
m2_torch = torch.randn(2, 3)

# torch.matmul performs matrix multiplication
torch_result = torch.matmul(m1_torch, m2_torch)

# Show both input tensors
print('Matrix 1:\n', m1_torch)
print('Matrix 2:\n', m2_torch)

# Show the output tensor and its final shape
print('PyTorch matmul result:\n', torch_result)
print('Result shape:', torch_result.shape)

Matrix 1:
 tensor([[-0.1468,  0.7861],
        [ 0.9468, -1.1143],
        [ 1.6908, -0.8948]])
Matrix 2:
 tensor([[-0.3556,  1.2324,  0.1382],
        [-1.6822,  0.3177,  0.1328]])
PyTorch matmul result:
 tensor([[-1.2702,  0.0688,  0.0841],
        [ 1.5378,  0.8128, -0.0172],
        [ 0.9040,  1.7994,  0.1148]])
Result shape: torch.Size([3, 3])


## 4. Softmax Function
Softmax converts raw scores into probabilities that add up to 1.
It is commonly used in classification tasks where one input must be mapped to one of several categories.

In [ ]:
# These are raw scores, sometimes called logits
z = np.array([1, 2, 3], dtype=np.float64)

# Softmax formula for each value is: softmax(z_i) = exp(z_i) / sum(exp(z))
# Step 1: compute exp(z_i) for each element
num = np.exp(z)
print('Exponentials of z:', num)

# Step 2: compute the denominator sum(exp(z))
den = np.sum(num)

# Step 3: divide each exp(z_i) by the denominator
softmax_numpy = num / den

# The result is a probability vector, so all values add up to 1
print('Numerator:', num)
print('Denominator:', den)
print('Softmax probabilities:', softmax_numpy)
print('Sum of probabilities:', np.sum(softmax_numpy))

[ 2.71828183  7.3890561  20.08553692]
Numerator: [ 2.71828183  7.3890561  20.08553692]
Denominator: 30.19287485057736
Softmax probabilities: [0.09003057 0.24472847 0.66524096]
Sum of probabilities: 1.0


In [ ]:
# Create the same raw scores as a PyTorch tensor
z_torch = torch.tensor([1.0, 2.0, 3.0])

# Softmax formula: softmax(z_i) = exp(z_i) / sum(exp(z))
# dim=0 means apply the formula across this 1D tensor
softfunc = nn.Softmax(dim=0)
print('Softmax function object:', softfunc)

# This applies the full softmax formula to z_torch
sigma_torch = softfunc(z_torch)

# The output values are probabilities, so their total is 1
print('Softmax probabilities:', sigma_torch)
print('Sum of probabilities:', torch.sum(sigma_torch))

Softmax function object: Softmax(dim=0)
Softmax probabilities: tensor([0.0900, 0.2447, 0.6652])
Sum of probabilities: tensor(1.)


## 5. Logarithms, Entropy, and Cross-Entropy
The logarithm is commonly used in loss functions because it turns probabilities into a scale that penalizes wrong confident predictions strongly.
Entropy measures uncertainty in a probability distribution. Cross-entropy compares predicted probabilities with the target distribution.

In [ ]:
# Create a small NumPy array
x = np.array([1, 2, 3], dtype=np.float64)

# Log formula: log([x1, x2, x3]) = [log(x1), log(x2), log(x3)]
# Here np.log means the natural logarithm, written as ln(x) in math
print('Values:', x)
print('Natural log of x:', np.log(x))

Values: [1. 2. 3.]
Natural log of x: [0.         0.69314718 1.09861229]


In [ ]:
# A probability distribution for three classes
probabilities = np.array([0.7, 0.2, 0.1], dtype=np.float64)

# One-hot target means the first class is the correct answer
target = np.array([1.0, 0.0, 0.0], dtype=np.float64)

# Entropy formula: H(p) = -sum(p * log(p))
# This measures how uncertain the probability distribution is
entropy = -np.sum(probabilities * np.log(probabilities))

# Cross-entropy formula: CE(y, p) = -sum(y * log(p))
# Here y is the target and p is the predicted probability distribution
cross_entropy = -np.sum(target * np.log(probabilities))

# If the target is one-hot like [1, 0, 0], cross-entropy becomes -log(p_correct_class)
print('Probabilities:', probabilities)
print('Entropy:', entropy)
print('Cross-entropy for the target class:', cross_entropy)

Probabilities: [0.7 0.2 0.1]
Entropy: 0.8018185525433372
Cross-entropy for the target class: 0.35667494393873245


In [ ]:
# Logarithms using PyTorch
torch_x = torch.tensor([1.0, 2.0, 3.0])

# torch.log computes the natural logarithm, written as ln(x) in math
# Formula: log([x1, x2, x3]) = [log(x1), log(x2), log(x3)]
print('Values:', torch_x)
print('Natural log using torch.log:', torch.log(torch_x))

## 6. Key Takeaways
- A vector is a 1D tensor.
- A matrix is a 2D tensor.
- Higher-dimensional tensors are used throughout deep learning for data, weights, biases, and intermediate computations.
- PyTorch mirrors many NumPy operations, which makes it easier to learn if you already know NumPy.

In [ ]:
# Create two 1D tensors
x1 = torch.tensor([1, 2, 3])
x2 = torch.tensor([10, 20, 30])

# For 1D tensors, matmul behaves like a dot product
# It multiplies matching positions and adds the results
print('Dot product using torch.matmul:', torch.matmul(x1, x2))

C:\Users\veguntur\AppData\Local\Temp\ipykernel_46772\664623310.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4483.)
  torch.matmul(x1, x2.T)


tensor(140)

In [ ]:
# Practice cell

# Dot product formula: a . b = sum(a_i * b_i)
practice_a = torch.tensor([2, 4, 6])
practice_b = torch.tensor([1, 3, 5])

print('Practice vector A:', practice_a)
print('Practice vector B:', practice_b)
print('Practice dot product:', torch.dot(practice_a, practice_b))
print('---------------------------------------------------------')

# Softmax formula: softmax(x_i) = exp(x_i) / sum(exp(x))
arr = [1, 2, 3, 4]
tensor_arr = torch.tensor(arr, dtype=torch.float32)
e_tensor_arr = torch.exp(tensor_arr)
print('Exponentials of tensor_arr:', e_tensor_arr)
denominator = torch.sum(e_tensor_arr)
print('Denominator:', denominator)
print('Softmax probabilities:', e_tensor_arr / denominator)
print('---------------------------------------------------------')

# The nn.Softmax object applies the same softmax formula automatically
print('Softmax function by nn object')
torch_arr = torch.tensor([1.0, 2.0, 3.0])
softfunc = nn.Softmax(dim=0)
print('Softmax function object:', softfunc)
print('Softmax probabilities:', softfunc(torch_arr))
print('---------------------------------------------------------')

Practice vector A: tensor([2, 4, 6])
Practice vector B: tensor([1, 3, 5])
Practice dot product: tensor(44)
---------------------------------------------------------
Exponentials of tensor_arr: tensor([ 2.7183,  7.3891, 20.0855, 54.5981])
Denominator: tensor(84.7910)
Softmax probabilities: tensor([0.0321, 0.0871, 0.2369, 0.6439])
---------------------------------------------------------
Softmax fuction by nn Object
Softmax function object: Softmax(dim=0)
Softmax probabilities: tensor([0.0900, 0.2447, 0.6652])
---------------------------------------------------------
